language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: CPsiMff/Ol+W3v/vh07qdVYEMh4wQi7KxWdQXAofhcF5P3IScYlRu1IDcJPQE1OokIlqnN++L/hsNaIDur3tAN7h3/iOmWUAdRGqzRuX0r3GrUWb7Xdhy8w3aTPu50OPn2OTZo2EuFzGOxto4bL5lm/G/WVxwPKwLQ8ncv1RLII=
  - secure: QuYxeKGWWbTncoI5V8a0puD6mpJsFcxbM16sL7FtO9FPYiDHctkRJlucxzfNzIQnuQVpEAwV33ZtDJMI8PCoPDLuN6is/FgW9ru06aAsBquFgXPO4erJij82bTXAwQUY48wL7BbF5f+hsPoj6fgkPsTFPKBd9RSJscz77O6Wkb0=
